### ISSUE TITLE
issues while installing the awesome configs

### ISSUE THREAD

**Issue by sanatg** [elenapan/dotfiles#162] opened 2021-10-21 05:32 UTC
Hi @elenapan i was copying your awesomewm configs to my configs directory and after doing that when i switched from cinnamon to  awesomewm it showed this error:
![awesome](https://user-images.githubusercontent.com/62789975/138217084-eee34f22-2059-4fae-a74b-d65de893d10b.jpeg)
and there was no change in the default screen.

what can i do to resolve it ?? i am using Linux Mint 20.1 cinnamon currently
and yes i built awesomewm from source through the master branch.

thanks in advance

**Comment by AliChraghi** [comment] 2022-01-25 21:51
duplicate of #42

**Closed** 2023-10-29 05:10 UTC
