### ISSUE TITLE
client.lua:1845: assertion failed!

### ISSUE THREAD

**Issue by marvelman3284** [elenapan/dotfiles#119] opened 2020-09-20 15:32 UTC
I followed your tutorial in the readme.md, so when I switch to aweseomeWM I get this error:

```**Oops, an error happend!**
/usr/share/awesome/lib/awful/-client.lua:1845: assertion failed!
```
OS:Manjaro
Date:September 20, 2020
If you need any other info let me know!
![image](https://user-images.githubusercontent.com/58921302/93716052-2e7fef80-fb3b-11ea-8f5d-c2a70aebdf64.jpeg)

**Comment by marvelman3284** [comment] 2020-09-20 15:53
![Uploading 93715531...]

**Comment by elenapan** [comment] 2020-09-21 13:18
Hi there,

That is an error I haven't seen before. Does it happen as soon as you login, or after doing some action (like switching windows)?

If possible, could you follow the troubleshooting instructions [here](https://github.com/elenapan/dotfiles/wiki/Troubleshooting#how-do-i-debug-my-configuration) in order to provide me with some logs?

Thank you.

**Comment by marvelman3284** [comment] 2020-09-21 13:32
Hi, 
Thanks for helping me!
Here is the output of `awesome -v`:
```marvelman3284@my-name-pc ~]$ awesome -v
awesome v4.3-881-gca29aa191-dirty (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no
```
The error occurs as soon as I switch to my awesomeWM session and enter my password. My screen freezes once I hit enter and the error pops up. In regards to getting logs, I am a linux noob and wasn't able to find the `~/.xsession-errors` file. Is that something that's only available in the awesomeWM session? If so then I wouldn't be able to get to that because as I said before I can not even get into awesome, I am just stuck on the loading screen.

**Comment by elenapan** [comment] 2020-09-21 13:49
The `~/.xsession-errors` file could sometimes be missing, depending on which display manager (login screen) you are using.

In that case, you could login with something other than Awesome and try the `Xephyr` solution at the bottom of the troubleshooting article I linked in my last message.

**Comment by marvelman3284** [comment] 2020-09-21 13:59
[output.txt](https://github.com/elenapan/dotfiles/files/5255782/output.txt)
Here is my console output if I try to use `Xephyr` section in the troubleshooting article.

**Comment by marvelman3284** [comment] 2020-09-21 19:58
Did you need more information?

**Comment by elenapan** [comment] 2020-09-22 22:26
Alright then.

Make the following change in `~/.config/awesome/rc.lua` in order to disable the `window_switcher` widget which could be responsible for this error:
```diff
-    require("elemental.window_switcher")
+    -- require("elemental.window_switcher")
```

If, after doing this and relogging with AwesomeWM, you still get the error, try logging in with the default AwesomeWM configuration by temporarily renaming your `~/.config/awesome` folder to something else:

```shell
mv ~/.config/awesome ~/.config/awesome-backup
```

When logging in you should now be dropped into the default, uncustomized AwesomeWM desktop. Let me know if the error is still there in that case.

> Did you need more information?

Nope, I was just busy with real life stuff.

**Comment by dsanchezlc** [comment] 2020-09-24 08:34
I can confirm this error goes away after commenting out that window switcher line.

**Comment by nystins** [comment] 2020-09-26 17:52
I have this problem too, when i disconnect my other monitor and only use 1 monitor, the problem goes away.

**Comment by elenapan** [comment] 2020-09-26 22:01
Thank you all, I will investigate.

**Comment by psychon** [comment] 2020-09-27 05:11
Assuming I got the line number right, the error occurs here (others who can reproduce the error: feel free to check with your local files): https://github.com/awesomeWM/awesome/blob/ca29aa191f1d17031eb5a8a76e27a87877ac9937/lib/awful/client.lua#L1748

There is only one call to `enable_tracking` in this repo. It is in `window_switcher_hide()`: https://github.com/elenapan/dotfiles/blob/0c33554f8e3a7b471b6855aacce5bcaf206b4e99/config/awesome/elemental/window_switcher.lua#L159
So to me, it seems like something somehow manages to call `window_switcher_hide()` without having called `window_switcher_show()` first: https://github.com/elenapan/dotfiles/blob/0c33554f8e3a7b471b6855aacce5bcaf206b4e99/config/awesome/elemental/window_switcher.lua#L212

However, I do not see what is actually going on / where the issue is.....

**Comment by elenapan** [comment] 2020-09-27 14:56
Thank you. It was `window_switcher_hide()` being called unnecessarily whenever a monitor was connected.

```lua
awful.screen.connect_for_each_screen(function(s)
    -- ...

    -- Center window switcher whenever its height changes
    s.window_switcher:connect_signal("property::height", function()
        awful.placement.centered(s.window_switcher, { honor_workarea = true, honor_padding = true })
        if get_num_clients(s) == 0 then
            window_switcher_hide() -- <-- this one
        end
    end)
end)
```

I have pushed the fix in f2730f5. People who had this error, let me know if its alright now.

**Comment by marvelman3284** [comment] 2020-09-27 15:21
I will check when I get home, thanks for all your help!

**Comment by nystins** [comment] 2020-09-27 18:41
Works well for me, ty

**Comment by dsanchezlc** [comment] 2020-10-06 11:35
The error does not show now. I think this issue can be closed.

**Comment by elenapan** [comment] 2020-10-07 13:44
Thank you everyone for the update.

Closing this as it seems solved. Otherwise, feel free to comment and I will re-open it.

**Closed by elenapan** 2020-10-07 13:44 UTC
