### ISSUE TITLE
The whole theme isnt working, i just get the "vanilla" awesomewm

### ISSUE THREAD

**Issue by xhxm** [elenapan/dotfiles#67] opened 2019-11-16 21:58 UTC
I'm on Ubuntu 18.04 and using AwesomeWM 4.3-4
It just says /home/user/.config/awesome/helper.lua:28: attempt to concatenate a nil value (local 'fg')
I have no clue whats wrong

**Comment by andreipavlenko** [comment] 2019-11-17 13:12
@xhxm You should build your awesomewm from source. See #58

**Comment by Hkyx** [comment] 2020-02-26 17:58
Hi @elenapan, @hellkitten9 

Got same problem on Manjaro, so want to try by building awesomewm myself instead of the aur repo.
If I check the official github, I saw 4.3 version only what steps did you took to build it for latest minor ? https://github.com/awesomeWM/awesome/tags
or the code is already merged into the master ? didn't saw info about that

ty, 

Hk

**Comment by elenapan** [comment] 2020-03-18 06:40
Closing as duplicate of #58

**Closed by elenapan** 2020-03-18 06:40 UTC
