### ISSUE TITLE
Lag Lag Lag 

### ISSUE THREAD

**Issue by n3m1s1s94** [elenapan/dotfiles#71] opened 2020-02-04 12:17 UTC
ISSUE
Lag. A lot if it every 10-15 seconds. Pretty much as described on https://www.reddit.com/r/awesomewm/comments/81fmsj/awesome_lags_a_little_bit/. There is also visible tearing at times for example when I quickly switch between workspaces. Specifically talking about audio, it does lag when I play something through mpv but not when i play audio through spotify. But definitely lags and skips when playing mpv. Suppose i was moving the mouse when it lags the whole mouse freezez up and suddenly jumps 2 secs later. Usuall  lag.
I'm assuming the issue is as described on https://awesomewm.org/apidoc/documentation/90-FAQ.md.html under input delay. I already have compton running but I don't know what to do about the second bit there.
SYS INFO
Installed archlabs with awesome which also uses your configs(Great work on it btw, please do finish it up if you ever get the time). The problem is there on that config as well. Pretty much the reason I even bothered looking for other configs. Installed your new config from here and the problem persists. 
EXTRA INFO 
Problem does not persist when I completely removed all configs and let awesome use it's defaults. I did install a config from https://github.com/szorfein/dotfiles as well and though there were many other issues that kept me from using the config, the lag issue was compmletely gone.
END
So yeah, that's that. Would love to have a solution to this it's killing me. 
Also since you use ubuntu, do you use it with wayland or x? And what commands did you run to get rid of gnome and all it's dependancies. If you used a flavor like xubuntu or something just replace the gnome in that question with the relevant de lol. That's literally like the only thing that's stopping me from giving it go myself tonight. Can I pretty please have them. Thinking of switching to deb or something cause i'm using this sys for work now so figured I could use the stability.

**Comment by elenapan** [comment] 2020-02-04 16:25
Hi there,

Sorry to hear about your lag, but don't worry, we will figure this out.

I have some questions for you:

- Have you monitored AwesomeWM's CPU and RAM usage? Anything abnormal? Do you notice any changes when the lag happens?
- Any AwesomeWM errors appearing in the notifications?

> I'm assuming the issue is as described on https://awesomewm.org/apidoc/documentation/90-FAQ.md.html under input delay. 

I do not use any blocking functions such as `io.popen` in my config, so it is probably not related to this.
But if you are using a compositor such as `compton` (recently got renamed to `picom`), you can try killing it and seeing if the problem persists.

There are 2 suspects here:
1. Garbage collection is too slow/lazy, and when the collector actually runs, the accumulated memory is so high that it takes a lot of time to free it, thus making you lag.

   At the bottom of `rc.lua` remove the comments from the last 2 lines so they look like this:
   ```lua
   collectgarbage("setpause", 110)
   collectgarbage("setstepmul", 1000)
   ```
   Then restart AwesomeWM and let me know if that improves the situation.
   Also it would be great if you could also provide Awesome's memory usage before and after you make this change.

2. Since you are lagging periodically (every 10-15 seconds), I am guessing that one of the deamons I am using to get system info is misbehaving.

   If the garbage collection trick did not work, or is not completely solving the problem, try commenting out the line `require("evil")` in `rc.lua`. This will make widgets such as CPU, volume, temperature bars etc stop working but will hopefully also get rid of your lag.

   Let me know if that helps and we will continue debugging from here to find which daemon is causing the problem.

--- 

I use X due to AwesomeWM not working on Wayland and also because I have an Nvidia GPU which does not work too well (or at all) on most Wayland compositors. 

I have not made any effort to get rid of the pre-installed bloat. I was not planning on keeping this installation for long so I just ignored it. I think you can run something like `sudo apt remove ubuntu-desktop` and then `sudo apt autoremove` but that will probably not remove everything. For gnome specific packages you can run `sudo apt remove --purge gnome*`. Still, you will have to hunt down some other pre-installed packages by hand.

If you want a minimal + stable experience, you can use [Ubuntu's `mini.iso`](https://help.ubuntu.com/community/Installation/MinimalCD) which is based on the current LTS release, and is similar to an Arch installation, but way easier since it has a very sleek terminal UI.
Another option is [Debian's netinst](https://www.debian.org/CD/netinst/) image. Just make sure to uncheck the "Desktop environment" checkbox when you reach the "software selection" stage.

Personally, I am waiting until April for Ubuntu's 20.04 LTS release which will come with an updated `mini.iso`.

**Comment by n3m1s1s94** [comment] 2020-02-06 09:56
Hello again thanks for the super quick reply :D. So I did go through your message and there's definitely a spike in cpu ussage when the lag occurs. Unfortunately I haven't yet tried any of the suggestions you had like disbaling the widget and that garbage collection edit because I have work and my boss is on my neck at work thanks to this important project and shit. Unfortuanetly that means I sleep like a little bitch once I'm back home and it's back to work in the morn so if it's not too bad could you give me till friday night or sat morning. I promise I won't ghost you and I'll try your suggestions and get back to you asap. Its thursday rn where i'm at. I would try tonight but i doubt ill be awake long enought for that. Sorry for the bother. You're awesome. Thank you again for your time and patience. And the awesome theme-ing of course. Bye for now and talk to oyu soon.

**Comment by elenapan** [comment] 2020-02-06 11:23
No rush, you can try this whenever you have time. Take care.

**Comment by n3m1s1s94** [comment] 2020-02-08 14:43
Hi again. It was the last one the widgets. I'm still on the archlabs config and it was the same issue on that as well. Had to comment out line 168 or near-abouts. Thank you so much. I feel I can finally use it comfortably now even though there's a little bit of tearing but I'm sure I'll manage to fix that soon enough. 
So excited to be joining the Awesomewm gang lol (^-^). Thanks again for your patience. Take care and bye bye <3

**Comment by elenapan** [comment] 2020-02-10 02:52
Ok  it is one of the widgets then. You can re-enable `require("evil")` and go to `~/.config/awesome/evil/init.lua`. You will see something like this:
```lua
require("evil.volume")
require("evil.battery")
require("evil.cpu")
require("evil.temperature")
require("evil.ram")
require("evil.weather")
require("evil.mpd")
require("evil.brightness")
require("evil.spotify")
```
 Try disabling them all except one. Do this for all of them in order to find which one makes you lag.

**Comment by n3m1s1s94** [comment] 2020-02-14 07:19
Cool. Again work all week. Imma try over the weekend and get back at ya'. 
I have to say though I freaking love awesome now that's it's actually usuable. I'm having an absolute blast with it. Hands down my favorite wm upto now. I'm using your archlabs dots for now. Kinda tryna merge this and skyfall soon lol.

I've used i3 and dwm in the past and flexability this has in comparisn is legit, especially between using the keyboard and mouse for desktop control. And it sort of feels more modern as well especially with some of the apps with newer design asthetics and I especially love how smooth and quick the transition is to floating which doesn't suck unlike even the great i3 and dwm. It makes it so smooth to switch to the mouse from the keyboard which I hacve to do very often because I have to use libre office for work and google maps and then theres spotify, not to mention more than half the sites that are quicker and easier with a mouse even in qute. They just be designed that way I guess. 

Anyway just wanted to say thank you for making it possible for me to finally give awesome a go. Absolutely loving it. 
Have a great day. Get back to you with the culprits over the weekend. Buh-bye.

**Comment by n3m1s1s94** [comment] 2020-02-19 18:24
Got it. It was the evil.temprature bit. Turned it off and all's smooth. Turned everything else off and just left evil.temprature on and it lagged then as well. So definitely temprature. 
Sorry I took my time. Work. 
Anyway I'm working merging skyfall and archlabs together so it's keeping me busy on the weekends when i'm not gaming lol. 
No major issues except fonts. I've installed all the fonts you said to but your zsh theme just won't display correctly them 3 arrows. They just be weird blocks. And i'm almost sure this might be exclusive to kitty but the glyph rendering on ranger for music files is off.  Apart from being so weird about rendering images that is. I think i might need to copy paste the required glyphs again after installing the fonts or something. 
I did have an issue in your skyfall gtk theme where if im truing to select a file using the gui that comes up say when trying to upload a file to gdrive on firefox or save something in libre, the left panel where the different home folders are in a list, the higlighed one is completely covered by a purple bar. no text no nothing. [Here's](-https://imgur.com/a/Eu2rtV7) a picture

Anyway, I'll let you know how it comes along even though iit's going real slow thanks to work lol. Thank you so much again. Bye bye & take care :)

**Comment by elenapan** [comment] 2020-07-11 19:21
**temperature widget**: You can test if the `sensors` command lags when you run it in the terminal. If it does,
it is probably be due to [this issue](https://github.com/lm-sensors/lm-sensors/issues/99), which unfortunately is out of my hands.
You could try a different kernel or distro I guess.

---

**zsh prompt arrows**: I have lost the font that provided those arrows ever since I reinstalled my OS. I think it was from an old version of Nerd Fonts which I cannot find anymore. You should replace them with something else. I am using this character instead: `❯`

---

**Skyfall GTK theme**: I have now generated and uploaded an updated version of the skyfall GTK theme which fixes the issue you describe.

Closing, since the original issue is not caused by my configuration.

**Closed by elenapan** 2020-07-11 19:21 UTC
