### ISSUE TITLE
When I launch awesome it shows error

### ISSUE THREAD

**Issue by anonygituser** [elenapan/dotfiles#158] opened 2021-10-06 02:36 UTC
`error while running function!
stack traceback:
    /home/user/.config/awesome/rc.lua:189 in main chunk
error: /home/user/.config/awesome/rc.lua:189 attempt to call a nil value (field 'connect_signal')`

**Comment by DerpTaterTot** [comment] 2021-10-07 22:45
Did you install the git version of awesome?

**Comment by elenapan** [comment] 2021-12-29 03:26
Yep, this error should disappear if you install the git version of awesome.
Duplicate of https://github.com/elenapan/dotfiles/issues/42 (among others).

**Closed by elenapan** 2021-12-29 03:26 UTC
